[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--prefix=/opt/buildhome"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200